minimalDict = {
    "." : [['D'], ['C'], ],
    "/" : [['AC'], ['ABC'], ['ADC'], ],
    "[" : [['ABCD'], ['A', 'AD'], ['BC'], ],
    "]" : [['A', 'AD'], ['BC'], ['BADC'], ],
    "a" : [['BAD', 'ABCD'], ['BADCBAD'], ['ABCD', 'BAD'], ],
    "b" : [['BCBADC'], ['BC', 'CDB'], ['BC', 'BADC'], ['BCDC'], ],
    "d" : [['ABCD', 'AD'], ['DCDAD'], ['ADABCD'], ['ADCD'], ['ABCDAD'], ['DCD', 'AD'], ],
    "e" : [['BABCD'], ['CDABCD'], ],
    "f" : [['ABC', 'CD'], ['ABC', 'B'], ['ABC', 'C'], ['ABC', 'BA'], ],
    "h" : [['BC', 'BAD'], ['BCD'], ['BCBAD'], ['BC', 'CD'], ],
    "i" : [['AD', 'A'], ['BC', 'B'], ],
    "j" : [['A', 'AD'], ['B', 'BC'], ['A', 'ADC'], ],
    "k" : [['BC', 'C', 'DCD'], ['BC', 'ADCD'], ],
    "l" : [['AD'], ['BC'], ],
    "m" : [['BCBCBAD'], ['BCBADAD'], ['BCBCBC'], ],
    "n" : [['BCBAD'], ],
    "o" : [['ABCDA'], ['BCDAB'], ],
    "p" : [['BCBADC'], ['BCBAB'], ['BC', 'BADC'], ['BC', 'BAB'], ],
    "r" : [['BCBA'], ],
    "s" : [['ABADC'], ['ABCDC'], ],
    "t" : [['BA', 'BCD'], ['BA', 'AD'], ],
    "u" : [['BCDAD'], ],
    "v" : [['BCD', 'AD'], ['BC', 'ADC'], ['BADA'], ['BCDA'], ['BAD', 'AD'], ],
    "w" : [['BCBADA'], ['BCBDA'], ['BCBCDA'], ['BCDADA'], ],
    "z" : [['BACD'], ['BABCD'], ['BADCD'], ],
    "æ" : [['BCBAD'], ['BCDAD'], ['BABCBAD'], ['BCDABCD'], ['BCBABAD'], ],
    "ð" : [['BADCBA', 'BA'], ['BADCD', 'BA'], ],
    "ŋ" : [['BCBADC'], ['BADC'], ['BCBAD'], ['BAD'], ],
    "ɑ" : [['ABCD', 'AD'], ['ABCDAD'], ],
    "ɒ" : [['BCBADC'], ['BC', 'BADC'], ],
    "ɔ" : [['BADC'], ],
    "ə" : [['BADCD'], ['BADCBA'], ],
    "ɚ" : [['BADCD'], ['BADCBA'], ],
    "ɜ" : [['BABADC'], ['BADCDC'], ],
    "ɜ˞" : [['BABADC', 'A'], ['BADCDC', 'DA'], ['BADCDC', 'D'], ],
    "ɡ" : [['ABCDADC'], ['ABCD', 'ADC'], ],
    "ɪ" : [['B', 'BC', 'C'], ['BA', 'BC', 'CD'], ['A', 'AD', 'D'], ['BA', 'AD', 'CD'], ],
    "ɫ" : [['BC', 'BA'], ['BC', 'CD'], ['AD', 'CD'], ['AD', 'BA'], ],
    "ɯ" : [['BCDADAD'], ['BCBCDAD'], ],
    "ɱ" : [['BCBADADC'], ['BCBCBADC'], ['BCDADAD'], ],
    "ɹ" : [['CDAD'], ],
    "ɻ" : [['CDAD'], ],
    "ɾ" : [['CBA'], ],
    "ʃ" : [['ABC'], ['ADC'], ],
    "ʊ" : [['BCDA'], ],
    "ʌ" : [['CBCD'], ['CBAD'], ['CDAD'], ],
    "ʒ" : [['BABADC'], ['BADCDC'], ],
    "ʔ" : [['BAD'], ['BABC'], ],
    "ˈ" : [['B'], ['A'], ],
    "ˌ" : [['D'], ['C'], ],
    "ː" : [['B', 'C'], ['A', 'D'], ],
    "θ" : [['BCDAB', 'CD'], ['ABCDA', 'BA'], ['ABCDA', 'CD'], ['BCDAB', 'BA'], ],
};
